// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/teamlumos/terraform-provider-lumos/internal/sdk/internal/utils"
	"github.com/teamlumos/terraform-provider-lumos/internal/sdk/models/shared"
	"net/http"
)

type CreateAppstoreRequestablePermissionAppstoreRequestablePermissionsPostRequest struct {
	// Include inherited configurations from parent app.
	IncludeInheritedConfigs    *bool                             `default:"true" queryParam:"style=form,explode=true,name=include_inherited_configs"`
	RequestablePermissionInput shared.RequestablePermissionInput `request:"mediaType=application/json"`
}

func (c CreateAppstoreRequestablePermissionAppstoreRequestablePermissionsPostRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateAppstoreRequestablePermissionAppstoreRequestablePermissionsPostRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateAppstoreRequestablePermissionAppstoreRequestablePermissionsPostRequest) GetIncludeInheritedConfigs() *bool {
	if c == nil {
		return nil
	}
	return c.IncludeInheritedConfigs
}

func (c *CreateAppstoreRequestablePermissionAppstoreRequestablePermissionsPostRequest) GetRequestablePermissionInput() shared.RequestablePermissionInput {
	if c == nil {
		return shared.RequestablePermissionInput{}
	}
	return c.RequestablePermissionInput
}

type CreateAppstoreRequestablePermissionAppstoreRequestablePermissionsPostResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful Response
	RequestablePermissionOutput *shared.RequestablePermissionOutput
	// Validation Error
	HTTPValidationError *shared.HTTPValidationError
}

func (c *CreateAppstoreRequestablePermissionAppstoreRequestablePermissionsPostResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateAppstoreRequestablePermissionAppstoreRequestablePermissionsPostResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateAppstoreRequestablePermissionAppstoreRequestablePermissionsPostResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *CreateAppstoreRequestablePermissionAppstoreRequestablePermissionsPostResponse) GetRequestablePermissionOutput() *shared.RequestablePermissionOutput {
	if c == nil {
		return nil
	}
	return c.RequestablePermissionOutput
}

func (c *CreateAppstoreRequestablePermissionAppstoreRequestablePermissionsPostResponse) GetHTTPValidationError() *shared.HTTPValidationError {
	if c == nil {
		return nil
	}
	return c.HTTPValidationError
}
