// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/teamlumos/terraform-provider-lumos/internal/sdk/internal/utils"
	"github.com/teamlumos/terraform-provider-lumos/internal/sdk/models/shared"
	"github.com/teamlumos/terraform-provider-lumos/internal/sdk/types"
	"net/http"
)

type Files struct {
	FileName string `multipartForm:"name=fileName"`
	Content  []byte `multipartForm:"content"`
}

func (f *Files) GetFileName() string {
	if f == nil {
		return ""
	}
	return f.FileName
}

func (f *Files) GetContent() []byte {
	if f == nil {
		return []byte{}
	}
	return f.Content
}

type CreateFoundDocumentMultipartRequestBody struct {
	// A unique identifier for the contract being uploaded. This can be an ID from an external system like Coupa, an internal ID such as a PO number, or simply the name of the file.
	UniqueIdentifier string `multipartForm:"name=unique_identifier"`
	// A list of files related to a vendor agreement. For example, the Order Form, Quote, MSA, or Terms and Conditions.
	Files []Files `multipartForm:"file,name=files"`
	// The name of the vendor associated with this document
	VendorName *string `multipartForm:"name=vendor_name"`
	// The start date of the attached contract
	StartDate *types.Date `multipartForm:"name=start_date"`
	// The end date of the attached contract
	EndDate *types.Date `multipartForm:"name=end_date"`
	// The ID of the app that sourced this document. For example, if you are using this API to create a custom Google Drive integration, you might include the ID for the Google Workspaceapp in Lumos. This determines which app's logo is displayed in Lumos.
	SourceAppID *string `multipartForm:"name=source_app_id"`
}

func (c CreateFoundDocumentMultipartRequestBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateFoundDocumentMultipartRequestBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateFoundDocumentMultipartRequestBody) GetUniqueIdentifier() string {
	if c == nil {
		return ""
	}
	return c.UniqueIdentifier
}

func (c *CreateFoundDocumentMultipartRequestBody) GetFiles() []Files {
	if c == nil {
		return []Files{}
	}
	return c.Files
}

func (c *CreateFoundDocumentMultipartRequestBody) GetVendorName() *string {
	if c == nil {
		return nil
	}
	return c.VendorName
}

func (c *CreateFoundDocumentMultipartRequestBody) GetStartDate() *types.Date {
	if c == nil {
		return nil
	}
	return c.StartDate
}

func (c *CreateFoundDocumentMultipartRequestBody) GetEndDate() *types.Date {
	if c == nil {
		return nil
	}
	return c.EndDate
}

func (c *CreateFoundDocumentMultipartRequestBody) GetSourceAppID() *string {
	if c == nil {
		return nil
	}
	return c.SourceAppID
}

type CreateFoundDocumentMultipartResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful Response
	Any any
	// Validation Error
	HTTPValidationError *shared.HTTPValidationError
}

func (c *CreateFoundDocumentMultipartResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateFoundDocumentMultipartResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateFoundDocumentMultipartResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *CreateFoundDocumentMultipartResponse) GetAny() any {
	if c == nil {
		return nil
	}
	return c.Any
}

func (c *CreateFoundDocumentMultipartResponse) GetHTTPValidationError() *shared.HTTPValidationError {
	if c == nil {
		return nil
	}
	return c.HTTPValidationError
}
