// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: d20cc6ed92a6

package operations

import (
	"github.com/teamlumos/terraform-provider-lumos/internal/sdk/models/shared"
	"net/http"
)

type DeleteAccessReviewAppRequest struct {
	AccessReviewID string `pathParam:"style=simple,explode=false,name=access_review_id"`
	ArdaID         string `pathParam:"style=simple,explode=false,name=arda_id"`
}

func (d *DeleteAccessReviewAppRequest) GetAccessReviewID() string {
	if d == nil {
		return ""
	}
	return d.AccessReviewID
}

func (d *DeleteAccessReviewAppRequest) GetArdaID() string {
	if d == nil {
		return ""
	}
	return d.ArdaID
}

type DeleteAccessReviewAppResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Validation Error
	HTTPValidationError *shared.HTTPValidationError
}

func (d *DeleteAccessReviewAppResponse) GetContentType() string {
	if d == nil {
		return ""
	}
	return d.ContentType
}

func (d *DeleteAccessReviewAppResponse) GetStatusCode() int {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DeleteAccessReviewAppResponse) GetRawResponse() *http.Response {
	if d == nil {
		return nil
	}
	return d.RawResponse
}

func (d *DeleteAccessReviewAppResponse) GetHTTPValidationError() *shared.HTTPValidationError {
	if d == nil {
		return nil
	}
	return d.HTTPValidationError
}
