// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 415afdf2b0f9

package operations

import (
	"github.com/teamlumos/terraform-provider-lumos/internal/sdk/internal/utils"
	"github.com/teamlumos/terraform-provider-lumos/internal/sdk/models/shared"
	"net/http"
)

type GetAppstorePreApprovalRulesForAppAppstorePreApprovalRulesGetRequest struct {
	// Filters preapproval rules by the ID of the app to which they belong.
	AppID *string `queryParam:"style=form,explode=true,name=app_id"`
	// Page number
	Page *int64 `default:"1" queryParam:"style=form,explode=true,name=page"`
	// Page size
	Size *int64 `default:"50" queryParam:"style=form,explode=true,name=size"`
}

func (g GetAppstorePreApprovalRulesForAppAppstorePreApprovalRulesGetRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetAppstorePreApprovalRulesForAppAppstorePreApprovalRulesGetRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetAppstorePreApprovalRulesForAppAppstorePreApprovalRulesGetRequest) GetAppID() *string {
	if g == nil {
		return nil
	}
	return g.AppID
}

func (g *GetAppstorePreApprovalRulesForAppAppstorePreApprovalRulesGetRequest) GetPage() *int64 {
	if g == nil {
		return nil
	}
	return g.Page
}

func (g *GetAppstorePreApprovalRulesForAppAppstorePreApprovalRulesGetRequest) GetSize() *int64 {
	if g == nil {
		return nil
	}
	return g.Size
}

type GetAppstorePreApprovalRulesForAppAppstorePreApprovalRulesGetResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful Response
	PagePreApprovalRuleOutput *shared.PagePreApprovalRuleOutput
	// Validation Error
	HTTPValidationError *shared.HTTPValidationError
}

func (g *GetAppstorePreApprovalRulesForAppAppstorePreApprovalRulesGetResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetAppstorePreApprovalRulesForAppAppstorePreApprovalRulesGetResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetAppstorePreApprovalRulesForAppAppstorePreApprovalRulesGetResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetAppstorePreApprovalRulesForAppAppstorePreApprovalRulesGetResponse) GetPagePreApprovalRuleOutput() *shared.PagePreApprovalRuleOutput {
	if g == nil {
		return nil
	}
	return g.PagePreApprovalRuleOutput
}

func (g *GetAppstorePreApprovalRulesForAppAppstorePreApprovalRulesGetResponse) GetHTTPValidationError() *shared.HTTPValidationError {
	if g == nil {
		return nil
	}
	return g.HTTPValidationError
}
