// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy/terraform-provider-lumos/internal/sdk/internal/utils"
	"github.com/speakeasy/terraform-provider-lumos/internal/sdk/models/shared"
	"net/http"
)

type GetGroupMembershipRequest struct {
	GroupID string `pathParam:"style=simple,explode=false,name=group_id"`
	Page    *int64 `default:"1" queryParam:"style=form,explode=true,name=page"`
	Size    *int64 `default:"50" queryParam:"style=form,explode=true,name=size"`
}

func (g GetGroupMembershipRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetGroupMembershipRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *GetGroupMembershipRequest) GetGroupID() string {
	if o == nil {
		return ""
	}
	return o.GroupID
}

func (o *GetGroupMembershipRequest) GetPage() *int64 {
	if o == nil {
		return nil
	}
	return o.Page
}

func (o *GetGroupMembershipRequest) GetSize() *int64 {
	if o == nil {
		return nil
	}
	return o.Size
}

type GetGroupMembershipResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful Response
	PageUser *shared.PageUser
	// Validation Error
	HTTPValidationError *shared.HTTPValidationError
}

func (o *GetGroupMembershipResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetGroupMembershipResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetGroupMembershipResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetGroupMembershipResponse) GetPageUser() *shared.PageUser {
	if o == nil {
		return nil
	}
	return o.PageUser
}

func (o *GetGroupMembershipResponse) GetHTTPValidationError() *shared.HTTPValidationError {
	if o == nil {
		return nil
	}
	return o.HTTPValidationError
}
