// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 0f313b855217

package operations

import (
	"github.com/teamlumos/terraform-provider-lumos/internal/sdk/internal/utils"
	"github.com/teamlumos/terraform-provider-lumos/internal/sdk/models/shared"
	"net/http"
)

type ListAccessPoliciesAccessPoliciesGetRequest struct {
	// Page number
	Page *int64 `default:"1" queryParam:"style=form,explode=true,name=page"`
	// Page size
	Size *int64 `default:"50" queryParam:"style=form,explode=true,name=size"`
	// Filter by policy name (case insensitive)
	Name *string `queryParam:"style=form,explode=true,name=name"`
}

func (l ListAccessPoliciesAccessPoliciesGetRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListAccessPoliciesAccessPoliciesGetRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListAccessPoliciesAccessPoliciesGetRequest) GetPage() *int64 {
	if l == nil {
		return nil
	}
	return l.Page
}

func (l *ListAccessPoliciesAccessPoliciesGetRequest) GetSize() *int64 {
	if l == nil {
		return nil
	}
	return l.Size
}

func (l *ListAccessPoliciesAccessPoliciesGetRequest) GetName() *string {
	if l == nil {
		return nil
	}
	return l.Name
}

type ListAccessPoliciesAccessPoliciesGetResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful Response
	PageAccessPolicyOutput *shared.PageAccessPolicyOutput
	// Validation Error
	HTTPValidationError *shared.HTTPValidationError
}

func (l *ListAccessPoliciesAccessPoliciesGetResponse) GetContentType() string {
	if l == nil {
		return ""
	}
	return l.ContentType
}

func (l *ListAccessPoliciesAccessPoliciesGetResponse) GetStatusCode() int {
	if l == nil {
		return 0
	}
	return l.StatusCode
}

func (l *ListAccessPoliciesAccessPoliciesGetResponse) GetRawResponse() *http.Response {
	if l == nil {
		return nil
	}
	return l.RawResponse
}

func (l *ListAccessPoliciesAccessPoliciesGetResponse) GetPageAccessPolicyOutput() *shared.PageAccessPolicyOutput {
	if l == nil {
		return nil
	}
	return l.PageAccessPolicyOutput
}

func (l *ListAccessPoliciesAccessPoliciesGetResponse) GetHTTPValidationError() *shared.HTTPValidationError {
	if l == nil {
		return nil
	}
	return l.HTTPValidationError
}
