// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/teamlumos/terraform-provider-lumos/internal/sdk/internal/utils"
	"github.com/teamlumos/terraform-provider-lumos/internal/sdk/models/shared"
	"net/http"
)

type ListAppsRequest struct {
	// Search against name, app instance identifier, and app class ID.
	NameSearch *string `queryParam:"style=form,explode=true,name=name_search"`
	// Search filter should be an exact match.
	ExactMatch *bool  `default:"false" queryParam:"style=form,explode=true,name=exact_match"`
	Page       *int64 `default:"1" queryParam:"style=form,explode=true,name=page"`
	Size       *int64 `default:"50" queryParam:"style=form,explode=true,name=size"`
}

func (l ListAppsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListAppsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ListAppsRequest) GetNameSearch() *string {
	if o == nil {
		return nil
	}
	return o.NameSearch
}

func (o *ListAppsRequest) GetExactMatch() *bool {
	if o == nil {
		return nil
	}
	return o.ExactMatch
}

func (o *ListAppsRequest) GetPage() *int64 {
	if o == nil {
		return nil
	}
	return o.Page
}

func (o *ListAppsRequest) GetSize() *int64 {
	if o == nil {
		return nil
	}
	return o.Size
}

type ListAppsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful Response
	PageApp *shared.PageApp
	// Validation Error
	HTTPValidationError *shared.HTTPValidationError
}

func (o *ListAppsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ListAppsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ListAppsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *ListAppsResponse) GetPageApp() *shared.PageApp {
	if o == nil {
		return nil
	}
	return o.PageApp
}

func (o *ListAppsResponse) GetHTTPValidationError() *shared.HTTPValidationError {
	if o == nil {
		return nil
	}
	return o.HTTPValidationError
}
