// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/teamlumos/terraform-provider-lumos/internal/sdk/models/shared"
	"net/http"
)

type ProcessVendrRequestCompletedWebhooksVendrRequestCompletedDomainAppUUIDPostRequestBody struct {
}

type ProcessVendrRequestCompletedWebhooksVendrRequestCompletedDomainAppUUIDPostRequest struct {
	DomainAppUUID string                                                                                 `pathParam:"style=simple,explode=false,name=domain_app_uuid"`
	RequestBody   *ProcessVendrRequestCompletedWebhooksVendrRequestCompletedDomainAppUUIDPostRequestBody `request:"mediaType=application/json"`
}

func (o *ProcessVendrRequestCompletedWebhooksVendrRequestCompletedDomainAppUUIDPostRequest) GetDomainAppUUID() string {
	if o == nil {
		return ""
	}
	return o.DomainAppUUID
}

func (o *ProcessVendrRequestCompletedWebhooksVendrRequestCompletedDomainAppUUIDPostRequest) GetRequestBody() *ProcessVendrRequestCompletedWebhooksVendrRequestCompletedDomainAppUUIDPostRequestBody {
	if o == nil {
		return nil
	}
	return o.RequestBody
}

type ProcessVendrRequestCompletedWebhooksVendrRequestCompletedDomainAppUUIDPostResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful Response
	Any any
	// Validation Error
	HTTPValidationError *shared.HTTPValidationError
}

func (o *ProcessVendrRequestCompletedWebhooksVendrRequestCompletedDomainAppUUIDPostResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ProcessVendrRequestCompletedWebhooksVendrRequestCompletedDomainAppUUIDPostResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ProcessVendrRequestCompletedWebhooksVendrRequestCompletedDomainAppUUIDPostResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *ProcessVendrRequestCompletedWebhooksVendrRequestCompletedDomainAppUUIDPostResponse) GetAny() any {
	if o == nil {
		return nil
	}
	return o.Any
}

func (o *ProcessVendrRequestCompletedWebhooksVendrRequestCompletedDomainAppUUIDPostResponse) GetHTTPValidationError() *shared.HTTPValidationError {
	if o == nil {
		return nil
	}
	return o.HTTPValidationError
}
