// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/teamlumos/terraform-provider-lumos/internal/sdk/models/shared"
	"net/http"
)

type UpdateAppRequest struct {
	AppID          string                `pathParam:"style=simple,explode=false,name=app_id"`
	AppInputCreate shared.AppInputCreate `request:"mediaType=application/json"`
}

func (o *UpdateAppRequest) GetAppID() string {
	if o == nil {
		return ""
	}
	return o.AppID
}

func (o *UpdateAppRequest) GetAppInputCreate() shared.AppInputCreate {
	if o == nil {
		return shared.AppInputCreate{}
	}
	return o.AppInputCreate
}

type UpdateAppResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful Response
	App *shared.App
	// Validation Error
	HTTPValidationError *shared.HTTPValidationError
}

func (o *UpdateAppResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *UpdateAppResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *UpdateAppResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *UpdateAppResponse) GetApp() *shared.App {
	if o == nil {
		return nil
	}
	return o.App
}

func (o *UpdateAppResponse) GetHTTPValidationError() *shared.HTTPValidationError {
	if o == nil {
		return nil
	}
	return o.HTTPValidationError
}
