// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: ac3eb0b05e0d

package operations

import (
	"github.com/teamlumos/terraform-provider-lumos/internal/sdk/models/shared"
	"net/http"
)

type UpdateAppRequest struct {
	AppID          string                `pathParam:"style=simple,explode=false,name=app_id"`
	AppInputUpdate shared.AppInputUpdate `request:"mediaType=application/json"`
}

func (u *UpdateAppRequest) GetAppID() string {
	if u == nil {
		return ""
	}
	return u.AppID
}

func (u *UpdateAppRequest) GetAppInputUpdate() shared.AppInputUpdate {
	if u == nil {
		return shared.AppInputUpdate{}
	}
	return u.AppInputUpdate
}

type UpdateAppResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful Response
	App *shared.App
	// Validation Error
	HTTPValidationError *shared.HTTPValidationError
}

func (u *UpdateAppResponse) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UpdateAppResponse) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UpdateAppResponse) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}

func (u *UpdateAppResponse) GetApp() *shared.App {
	if u == nil {
		return nil
	}
	return u.App
}

func (u *UpdateAppResponse) GetHTTPValidationError() *shared.HTTPValidationError {
	if u == nil {
		return nil
	}
	return u.HTTPValidationError
}
