// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: b0320ee9a810

package operations

import (
	"github.com/teamlumos/terraform-provider-lumos/internal/sdk/models/shared"
	"net/http"
)

type UpdateAppSettingsRequest struct {
	AppID           string                 `pathParam:"style=simple,explode=false,name=app_id"`
	AppSettingInput shared.AppSettingInput `request:"mediaType=application/json"`
}

func (u *UpdateAppSettingsRequest) GetAppID() string {
	if u == nil {
		return ""
	}
	return u.AppID
}

func (u *UpdateAppSettingsRequest) GetAppSettingInput() shared.AppSettingInput {
	if u == nil {
		return shared.AppSettingInput{}
	}
	return u.AppSettingInput
}

type UpdateAppSettingsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful Response
	AppSettingOutput *shared.AppSettingOutput
	// Validation Error
	HTTPValidationError *shared.HTTPValidationError
}

func (u *UpdateAppSettingsResponse) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UpdateAppSettingsResponse) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UpdateAppSettingsResponse) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}

func (u *UpdateAppSettingsResponse) GetAppSettingOutput() *shared.AppSettingOutput {
	if u == nil {
		return nil
	}
	return u.AppSettingOutput
}

func (u *UpdateAppSettingsResponse) GetHTTPValidationError() *shared.HTTPValidationError {
	if u == nil {
		return nil
	}
	return u.HTTPValidationError
}
