// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 9ea80b73dfdb

package shared

import (
	"encoding/json"
	"fmt"
)

type AccessReviewRemovalAction string

const (
	AccessReviewRemovalActionDeprovision AccessReviewRemovalAction = "DEPROVISION"
	AccessReviewRemovalActionSuspend     AccessReviewRemovalAction = "SUSPEND"
	AccessReviewRemovalActionDeactivate  AccessReviewRemovalAction = "DEACTIVATE"
	AccessReviewRemovalActionManual      AccessReviewRemovalAction = "MANUAL"
	AccessReviewRemovalActionWebhook     AccessReviewRemovalAction = "WEBHOOK"
)

func (e AccessReviewRemovalAction) ToPointer() *AccessReviewRemovalAction {
	return &e
}
func (e *AccessReviewRemovalAction) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "DEPROVISION":
		fallthrough
	case "SUSPEND":
		fallthrough
	case "DEACTIVATE":
		fallthrough
	case "MANUAL":
		fallthrough
	case "WEBHOOK":
		*e = AccessReviewRemovalAction(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AccessReviewRemovalAction: %v", v)
	}
}
