// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"github.com/teamlumos/terraform-provider-lumos/internal/sdk/internal/utils"
	"time"
)

// RequesterUser - The user who requested access. It's possible for one user to request access on another's behalf.
type RequesterUser struct {
	// The email of this user.
	Email *string `json:"email,omitempty"`
	// The family name of this user.
	FamilyName *string `json:"family_name,omitempty"`
	// The given name of this user.
	GivenName *string `json:"given_name,omitempty"`
	// The ID of this user.
	ID string `json:"id"`
	// The status of this user.
	Status *UserLifecycleStatus `json:"status,omitempty"`
}

func (o *RequesterUser) GetEmail() *string {
	if o == nil {
		return nil
	}
	return o.Email
}

func (o *RequesterUser) GetFamilyName() *string {
	if o == nil {
		return nil
	}
	return o.FamilyName
}

func (o *RequesterUser) GetGivenName() *string {
	if o == nil {
		return nil
	}
	return o.GivenName
}

func (o *RequesterUser) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *RequesterUser) GetStatus() *UserLifecycleStatus {
	if o == nil {
		return nil
	}
	return o.Status
}

// TargetUser - The user the request is for.
type TargetUser struct {
	// The email of this user.
	Email *string `json:"email,omitempty"`
	// The family name of this user.
	FamilyName *string `json:"family_name,omitempty"`
	// The given name of this user.
	GivenName *string `json:"given_name,omitempty"`
	// The ID of this user.
	ID string `json:"id"`
	// The status of this user.
	Status *UserLifecycleStatus `json:"status,omitempty"`
}

func (o *TargetUser) GetEmail() *string {
	if o == nil {
		return nil
	}
	return o.Email
}

func (o *TargetUser) GetFamilyName() *string {
	if o == nil {
		return nil
	}
	return o.FamilyName
}

func (o *TargetUser) GetGivenName() *string {
	if o == nil {
		return nil
	}
	return o.GivenName
}

func (o *TargetUser) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *TargetUser) GetStatus() *UserLifecycleStatus {
	if o == nil {
		return nil
	}
	return o.Status
}

// AccessRequest - API version of DomainAppSupportRequest.
type AccessRequest struct {
	// The ID of the app the request is for.
	AppID string `json:"app_id"`
	// The name of the app the request is for.
	AppName   string     `json:"app_name"`
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	// The ID of the access request.
	ID string `json:"id"`
	// The reason the user wrote for putting the access request into the given state.
	Notes                  map[string]string             `json:"notes,omitempty"`
	RequestablePermissions []RequestablePermissionOutput `json:"requestable_permissions,omitempty"`
	RequestedAt            *time.Time                    `json:"requested_at,omitempty"`
	// The user who requested access. It's possible for one user to request access on another's behalf.
	RequesterUser RequesterUser `json:"requester_user"`
	// The current status of the request.
	Status        SupportRequestStatus `json:"status"`
	SupporterUser *User                `json:"supporter_user,omitempty"`
	// The user the request is for.
	TargetUser TargetUser `json:"target_user"`
}

func (a AccessRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AccessRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *AccessRequest) GetAppID() string {
	if o == nil {
		return ""
	}
	return o.AppID
}

func (o *AccessRequest) GetAppName() string {
	if o == nil {
		return ""
	}
	return o.AppName
}

func (o *AccessRequest) GetExpiresAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.ExpiresAt
}

func (o *AccessRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *AccessRequest) GetNotes() map[string]string {
	if o == nil {
		return nil
	}
	return o.Notes
}

func (o *AccessRequest) GetRequestablePermissions() []RequestablePermissionOutput {
	if o == nil {
		return nil
	}
	return o.RequestablePermissions
}

func (o *AccessRequest) GetRequestedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.RequestedAt
}

func (o *AccessRequest) GetRequesterUser() RequesterUser {
	if o == nil {
		return RequesterUser{}
	}
	return o.RequesterUser
}

func (o *AccessRequest) GetStatus() SupportRequestStatus {
	if o == nil {
		return SupportRequestStatus("")
	}
	return o.Status
}

func (o *AccessRequest) GetSupporterUser() *User {
	if o == nil {
		return nil
	}
	return o.SupporterUser
}

func (o *AccessRequest) GetTargetUser() TargetUser {
	if o == nil {
		return TargetUser{}
	}
	return o.TargetUser
}
