// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 66a4dd52cdc6

package shared

import (
	"github.com/teamlumos/terraform-provider-lumos/internal/sdk/internal/utils"
)

type AccessPolicyInputAccessCondition struct {
}

type AccessPolicyInput struct {
	// The name of the access policy.
	Name string `json:"name"`
	// Explanation for why this policy exists.
	BusinessJustification string `json:"business_justification"`
	// List of apps granted by this access policy.
	Apps []AccessPolicyAppInput `json:"apps"`
	// The condition determining which identities qualify for this policy. Required if is_everyone_condition is not True. This is a recursive structure that can contain nested conditions using 'and', 'or', and 'not' operators. See the Condition schema for full details.
	AccessCondition *AccessPolicyInputAccessCondition `json:"access_condition,omitempty"`
	// Whether the access policy applies to everyone. If true, access_condition is ignored. Otherwise, access_condition must be provided.
	IsEveryoneCondition *bool `default:"false" json:"is_everyone_condition"`
}

func (a AccessPolicyInput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AccessPolicyInput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AccessPolicyInput) GetName() string {
	if a == nil {
		return ""
	}
	return a.Name
}

func (a *AccessPolicyInput) GetBusinessJustification() string {
	if a == nil {
		return ""
	}
	return a.BusinessJustification
}

func (a *AccessPolicyInput) GetApps() []AccessPolicyAppInput {
	if a == nil {
		return []AccessPolicyAppInput{}
	}
	return a.Apps
}

func (a *AccessPolicyInput) GetAccessCondition() *AccessPolicyInputAccessCondition {
	if a == nil {
		return nil
	}
	return a.AccessCondition
}

func (a *AccessPolicyInput) GetIsEveryoneCondition() *bool {
	if a == nil {
		return nil
	}
	return a.IsEveryoneCondition
}
