// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: cada176284ca

package shared

// AccessPolicyAppOutput - An app granted by this access policy.
// Extends BaseApp with access-policy-specific fields.
type AccessPolicyAppOutput struct {
	// The ID of this app.
	ID string `json:"id"`
	// Whether requests created via this access policy are pre-approved.
	IsPreapproved bool `json:"is_preapproved"`
	// List of permissions granted for this app. Empty list means app-level grant.
	Permissions []AccessPolicyPermissionOutput `json:"permissions"`
}

func (a *AccessPolicyAppOutput) GetID() string {
	if a == nil {
		return ""
	}
	return a.ID
}

func (a *AccessPolicyAppOutput) GetIsPreapproved() bool {
	if a == nil {
		return false
	}
	return a.IsPreapproved
}

func (a *AccessPolicyAppOutput) GetPermissions() []AccessPolicyPermissionOutput {
	if a == nil {
		return []AccessPolicyPermissionOutput{}
	}
	return a.Permissions
}
