// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// AirbaseMilestoneEvent - Model of the input we'll get from Airbase's webhook call.
// To be completed when we get docs.
type AirbaseMilestoneEvent struct {
}
