// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 1ac671d308e7

package shared

type AllowedGroupsConfigInput struct {
	Type *AllowedGroupsConfigType `json:"type,omitempty"`
	// The groups allowed to request this permission.
	Groups []BaseGroup `json:"groups,omitempty"`
}

func (a *AllowedGroupsConfigInput) GetType() *AllowedGroupsConfigType {
	if a == nil {
		return nil
	}
	return a.Type
}

func (a *AllowedGroupsConfigInput) GetGroups() []BaseGroup {
	if a == nil {
		return nil
	}
	return a.Groups
}
