// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 720fa74e0d9f

package shared

// APIError - The V1 error envelope.
type APIError struct {
	// Human-readable summary of the error.
	Detail string    `json:"detail"`
	Type   ErrorType `json:"type"`
	// Stable machine-readable error code.
	Code string `json:"code"`
	// Field-level errors; empty for non-validation errors.
	Errors []APIErrorField `json:"errors,omitempty"`
}

func (a *APIError) GetDetail() string {
	if a == nil {
		return ""
	}
	return a.Detail
}

func (a *APIError) GetType() ErrorType {
	if a == nil {
		return ErrorType("")
	}
	return a.Type
}

func (a *APIError) GetCode() string {
	if a == nil {
		return ""
	}
	return a.Code
}

func (a *APIError) GetErrors() []APIErrorField {
	if a == nil {
		return nil
	}
	return a.Errors
}
