// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type App struct {
	// The ID of this app.
	ID string `json:"id"`
	// The non-unique ID of the service associated with this requestable permission. Depending on how it is sourced in Lumos, this may be the app's name, website, or other identifier.
	AppClassID string `json:"app_class_id"`
	// The non-unique ID of the instance associated with this app. This will be the Okta app id if it’s an Okta app, or will be marked as custom_app_import if manually uploaded into Lumos.
	InstanceID string `json:"instance_id"`
	// The user-friendly label of this app.
	UserFriendlyLabel string `json:"user_friendly_label"`
	// The status of this app. Possible values: 'DISCOVERED', 'NEEDS_REVIEW', 'APPROVED', 'BLOCKLISTED', 'DEPRECATED'
	Status DomainAppStatus `json:"status"`
	// The sources of this app.
	Sources []DiscoverySource `json:"sources"`
	// Determines whether users can request multiple permissions at once.This field will be removed in subsequent API versions.
	AllowMultiplePermissionSelection bool `json:"allow_multiple_permission_selection"`
	// The URL of the logo of this app.
	LogoURL *string `json:"logo_url,omitempty"`
	// The URL of the website of this app.
	WebsiteURL *string `json:"website_url,omitempty"`
	// The request instructions.
	RequestInstructions *string `json:"request_instructions,omitempty"`
}

func (o *App) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *App) GetAppClassID() string {
	if o == nil {
		return ""
	}
	return o.AppClassID
}

func (o *App) GetInstanceID() string {
	if o == nil {
		return ""
	}
	return o.InstanceID
}

func (o *App) GetUserFriendlyLabel() string {
	if o == nil {
		return ""
	}
	return o.UserFriendlyLabel
}

func (o *App) GetStatus() DomainAppStatus {
	if o == nil {
		return DomainAppStatus("")
	}
	return o.Status
}

func (o *App) GetSources() []DiscoverySource {
	if o == nil {
		return []DiscoverySource{}
	}
	return o.Sources
}

func (o *App) GetAllowMultiplePermissionSelection() bool {
	if o == nil {
		return false
	}
	return o.AllowMultiplePermissionSelection
}

func (o *App) GetLogoURL() *string {
	if o == nil {
		return nil
	}
	return o.LogoURL
}

func (o *App) GetWebsiteURL() *string {
	if o == nil {
		return nil
	}
	return o.WebsiteURL
}

func (o *App) GetRequestInstructions() *string {
	if o == nil {
		return nil
	}
	return o.RequestInstructions
}
