// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type AppApproversOutput struct {
	// Groups assigned as support request approvers.
	Groups []Group `json:"groups,omitempty"`
	// Users assigned as support request approvers.
	Users []User `json:"users,omitempty"`
}

func (o *AppApproversOutput) GetGroups() []Group {
	if o == nil {
		return nil
	}
	return o.Groups
}

func (o *AppApproversOutput) GetUsers() []User {
	if o == nil {
		return nil
	}
	return o.Users
}
