// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: fb145fbbdab7

package shared

type AppInputCreate struct {
	// The name of the app you're creating.
	Name string `json:"name"`
	// The category of the app you're creating. Possible values: 'Accounting & Finance', 'Marketing & Analytics', 'Content & Social Media', 'Sales & Support', 'Design & Creativity', 'IT & Security', 'Developers', 'HR & Learning', 'Office & Legal', 'Communication', 'Collaboration', 'Commerce & Marketplaces', 'Other', 'Internal'
	Category string `json:"category"`
	// The description of the app you're creating.
	Description string `json:"description"`
	// The URL of the logo of the app you're creating.
	LogoURL *string `json:"logo_url,omitempty"`
	// The URL of the website of the app you're creating.
	WebsiteURL *string `json:"website_url,omitempty"`
	// The request instructions.
	RequestInstructions *string `json:"request_instructions,omitempty"`
}

func (a *AppInputCreate) GetName() string {
	if a == nil {
		return ""
	}
	return a.Name
}

func (a *AppInputCreate) GetCategory() string {
	if a == nil {
		return ""
	}
	return a.Category
}

func (a *AppInputCreate) GetDescription() string {
	if a == nil {
		return ""
	}
	return a.Description
}

func (a *AppInputCreate) GetLogoURL() *string {
	if a == nil {
		return nil
	}
	return a.LogoURL
}

func (a *AppInputCreate) GetWebsiteURL() *string {
	if a == nil {
		return nil
	}
	return a.WebsiteURL
}

func (a *AppInputCreate) GetRequestInstructions() *string {
	if a == nil {
		return nil
	}
	return a.RequestInstructions
}
