// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type AppInputCreate struct {
	// The name of the app you're creating.
	Name *string `json:"name,omitempty"`
	// The category of the app you're creating.
	Category *string `json:"category,omitempty"`
	// The description of the app you're creating.
	Description *string `json:"description,omitempty"`
}

func (o *AppInputCreate) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *AppInputCreate) GetCategory() *string {
	if o == nil {
		return nil
	}
	return o.Category
}

func (o *AppInputCreate) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}
