// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ApproverOutput struct {
	Type ApproverType `json:"type"`
	// Optionally, the approver can be a user.
	User *User `json:"user,omitempty"`
	// Optionally, the approver can be a group.
	Group *Group `json:"group,omitempty"`
}

func (o *ApproverOutput) GetType() ApproverType {
	if o == nil {
		return ApproverType("")
	}
	return o.Type
}

func (o *ApproverOutput) GetUser() *User {
	if o == nil {
		return nil
	}
	return o.User
}

func (o *ApproverOutput) GetGroup() *Group {
	if o == nil {
		return nil
	}
	return o.Group
}
