// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 8a028a445044

package shared

import (
	"github.com/teamlumos/terraform-provider-lumos/internal/sdk/internal/utils"
)

type AppSettingInput struct {
	// AppStore App instructions that are shown to the requester.
	CustomRequestInstructions *string `json:"custom_request_instructions,omitempty"`
	// If set, requesting this app redirects the user to this URL instead of going through the normal access-request flow. Send null to clear an existing redirect; omit the field to leave it unchanged. Max 2048 characters.
	RedirectURL  *string                               `json:"redirect_url,omitempty"`
	RequestFlow  *AppStoreAppSettingsRequestFlowInput  `json:"request_flow,omitempty"`
	Provisioning *AppStoreAppSettingsProvisioningInput `json:"provisioning,omitempty"`
	// Whether the app is in the app store.
	InAppStore *bool `default:"false" json:"in_app_store"`
}

func (a AppSettingInput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AppSettingInput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AppSettingInput) GetCustomRequestInstructions() *string {
	if a == nil {
		return nil
	}
	return a.CustomRequestInstructions
}

func (a *AppSettingInput) GetRedirectURL() *string {
	if a == nil {
		return nil
	}
	return a.RedirectURL
}

func (a *AppSettingInput) GetRequestFlow() *AppStoreAppSettingsRequestFlowInput {
	if a == nil {
		return nil
	}
	return a.RequestFlow
}

func (a *AppSettingInput) GetProvisioning() *AppStoreAppSettingsProvisioningInput {
	if a == nil {
		return nil
	}
	return a.Provisioning
}

func (a *AppSettingInput) GetInAppStore() *bool {
	if a == nil {
		return nil
	}
	return a.InAppStore
}
