// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/teamlumos/terraform-provider-lumos/internal/sdk/internal/utils"
)

type AppSettingOutput struct {
	// AppStore App instructions that are shown to the requester.
	CustomRequestInstructions *string `json:"custom_request_instructions,omitempty"`
	// Request flow configuration to request access to app.
	RequestFlow *AppStoreAppSettingsRequestFlowOutput `json:"request_flow,omitempty"`
	// Provisioning flow configuration to request access to app.
	Provisioning *AppStoreAppSettingsProvisioningOutput `json:"provisioning,omitempty"`
	// Whether the app is in the app store.
	InAppStore *bool `default:"false" json:"in_app_store"`
}

func (a AppSettingOutput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AppSettingOutput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *AppSettingOutput) GetCustomRequestInstructions() *string {
	if o == nil {
		return nil
	}
	return o.CustomRequestInstructions
}

func (o *AppSettingOutput) GetRequestFlow() *AppStoreAppSettingsRequestFlowOutput {
	if o == nil {
		return nil
	}
	return o.RequestFlow
}

func (o *AppSettingOutput) GetProvisioning() *AppStoreAppSettingsProvisioningOutput {
	if o == nil {
		return nil
	}
	return o.Provisioning
}

func (o *AppSettingOutput) GetInAppStore() *bool {
	if o == nil {
		return nil
	}
	return o.InAppStore
}
