// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type AppStoreAppSettingsOutput struct {
	// AppStore App instructions that are shown to the requester.
	CustomRequestInstructions *string `json:"custom_request_instructions,omitempty"`
	// Request flow configuration to request access to app.
	RequestFlow *AppStoreAppSettingsRequestFlowOutput `json:"request_flow,omitempty"`
	// Provisioning flow configuration to request access to app.
	Provisioning *AppStoreAppSettingsProvisioningOutput `json:"provisioning,omitempty"`
}

func (o *AppStoreAppSettingsOutput) GetCustomRequestInstructions() *string {
	if o == nil {
		return nil
	}
	return o.CustomRequestInstructions
}

func (o *AppStoreAppSettingsOutput) GetRequestFlow() *AppStoreAppSettingsRequestFlowOutput {
	if o == nil {
		return nil
	}
	return o.RequestFlow
}

func (o *AppStoreAppSettingsOutput) GetProvisioning() *AppStoreAppSettingsProvisioningOutput {
	if o == nil {
		return nil
	}
	return o.Provisioning
}
