// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: b474119b5bfb

package shared

type AttributeInput struct {
	// The unique identifier of the custom attribute
	UniqueIdentifier *string `json:"unique_identifier,omitempty"`
	// The type of the attribute.
	Type *string `json:"type,omitempty"`
	// The name of the attribute.
	Name *string `json:"name,omitempty"`
}

func (a *AttributeInput) GetUniqueIdentifier() *string {
	if a == nil {
		return nil
	}
	return a.UniqueIdentifier
}

func (a *AttributeInput) GetType() *string {
	if a == nil {
		return nil
	}
	return a.Type
}

func (a *AttributeInput) GetName() *string {
	if a == nil {
		return nil
	}
	return a.Name
}
