// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type BaseInlineWebhook struct {
	// The ID of this inline webhook.
	ID string `json:"id"`
}

func (o *BaseInlineWebhook) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}
