// Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

package shared

type BaseUser struct {
	// The ID of this user.
	ID string `json:"id"`
}

func (o *BaseUser) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}
