// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 9fb7382b8fe8

package shared

import (
	"github.com/teamlumos/terraform-provider-lumos/internal/sdk/internal/utils"
)

// Settings - Non-secret configuration as a JSON object — e.g. host, port, region, or tenant / instance URL. Carries the per-deployment tuning an integration needs that isn't a credential; the accepted keys vary by integration and some integrations need none. Optional — defaults to an empty object.
type Settings struct {
}

// Auth - Credentials as a JSON object. **All secrets go here** — there are no top-level credential fields. The accepted keys depend on the integration and are validated server-side; see the per-integration request examples. Some integrations connect in-band from these credentials (e.g. an `api_key`, or an OAuth `client_id`/`client_secret`). Others require browser consent and are finished in the Lumos UI — for those, `auth` may be empty (`{}`) and the connection begins `PARTIALLY_CONNECTED`. Missing or wrong-shaped credentials are rejected with 400; credentials the third party rejects return 502.
type Auth struct {
}

type ConnectIntegrationInput struct {
	// Canonical identifier of the integration to connect, e.g. `okta.com`. Determines the credentials and settings the integration expects. Must be an integration Lumos supports for your domain; an unknown value is rejected with 400. Required — omitting it fails request validation with 422.
	AppID string `json:"app_id"`
	// Non-secret configuration as a JSON object — e.g. host, port, region, or tenant / instance URL. Carries the per-deployment tuning an integration needs that isn't a credential; the accepted keys vary by integration and some integrations need none. Optional — defaults to an empty object.
	Settings *Settings `json:"settings,omitempty"`
	// Credentials as a JSON object. **All secrets go here** — there are no top-level credential fields. The accepted keys depend on the integration and are validated server-side; see the per-integration request examples. Some integrations connect in-band from these credentials (e.g. an `api_key`, or an OAuth `client_id`/`client_secret`). Others require browser consent and are finished in the Lumos UI — for those, `auth` may be empty (`{}`) and the connection begins `PARTIALLY_CONNECTED`. Missing or wrong-shaped credentials are rejected with 400; credentials the third party rejects return 502.
	Auth *Auth `json:"auth,omitempty"`
	// Identifier of the specific tenant/instance being connected — e.g. an Okta org URL (`https://myorg.okta.com`) or an ICS tenant `sub` / slug. Disambiguates multiple instances of the same app within one domain and is echoed back (canonicalized) on the response. A caller-supplied value wins on connect; on reconnect the detected id wins so Lumos tracks vendor tenant renames. Optional — when omitted it is auto-detected from the credentials where possible; some multi-instance integrations return 400 when it can't be derived.
	AppInstanceIdentifier *string `default:"" json:"app_instance_identifier"`
	// Optional integration version override. Pins the connection to a specific integration implementation/version instead of the current default — used for staged rollouts and back-compat. Leave unset (`null`) to use the default version, which is correct for nearly all callers; an unregistered version is rejected with 400.
	Version *string `json:"version,omitempty"`
}

func (c ConnectIntegrationInput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ConnectIntegrationInput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ConnectIntegrationInput) GetAppID() string {
	if c == nil {
		return ""
	}
	return c.AppID
}

func (c *ConnectIntegrationInput) GetSettings() *Settings {
	if c == nil {
		return nil
	}
	return c.Settings
}

func (c *ConnectIntegrationInput) GetAuth() *Auth {
	if c == nil {
		return nil
	}
	return c.Auth
}

func (c *ConnectIntegrationInput) GetAppInstanceIdentifier() *string {
	if c == nil {
		return nil
	}
	return c.AppInstanceIdentifier
}

func (c *ConnectIntegrationInput) GetVersion() *string {
	if c == nil {
		return nil
	}
	return c.Version
}
