// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 35442c2a3d35

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/teamlumos/terraform-provider-lumos/internal/sdk/internal/utils"
)

// CustomAttributeScopeFilterInputGroup - Always CUSTOM_ATTRIBUTE.
type CustomAttributeScopeFilterInputGroup string

const (
	CustomAttributeScopeFilterInputGroupCustomAttribute CustomAttributeScopeFilterInputGroup = "CUSTOM_ATTRIBUTE"
)

func (e CustomAttributeScopeFilterInputGroup) ToPointer() *CustomAttributeScopeFilterInputGroup {
	return &e
}
func (e *CustomAttributeScopeFilterInputGroup) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "CUSTOM_ATTRIBUTE":
		*e = CustomAttributeScopeFilterInputGroup(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CustomAttributeScopeFilterInputGroup: %v", v)
	}
}

// CustomAttributeScopeFilterInput - Scope filter for “CUSTOM_ATTRIBUTE“ groups.
//
// Custom attributes are keyed by “name“ (the attribute label, e.g.
// "Department"). “type“ declares the attribute's type (STRING, INTEGER,
// DATETIME, USER, GROUP, SINGLESELECT, MULTISELECT).
type CustomAttributeScopeFilterInput struct {
	// Always CUSTOM_ATTRIBUTE.
	group CustomAttributeScopeFilterInputGroup `const:"CUSTOM_ATTRIBUTE" json:"group"`
	// Custom attribute label (e.g. 'Department'). Matches the label from scope_options.
	Name string `json:"name"`
	// Human-readable display label.
	Label string `json:"label"`
	// Value to filter by for this custom attribute.
	Value *string `json:"value,omitempty"`
	// Attribute type (STRING, INTEGER, DATETIME, USER, GROUP, SINGLESELECT, MULTISELECT).
	Type *string `json:"type,omitempty"`
}

func (c CustomAttributeScopeFilterInput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CustomAttributeScopeFilterInput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CustomAttributeScopeFilterInput) GetGroup() CustomAttributeScopeFilterInputGroup {
	return CustomAttributeScopeFilterInputGroupCustomAttribute
}

func (c *CustomAttributeScopeFilterInput) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CustomAttributeScopeFilterInput) GetLabel() string {
	if c == nil {
		return ""
	}
	return c.Label
}

func (c *CustomAttributeScopeFilterInput) GetValue() *string {
	if c == nil {
		return nil
	}
	return c.Value
}

func (c *CustomAttributeScopeFilterInput) GetType() *string {
	if c == nil {
		return nil
	}
	return c.Type
}
