// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: a5c345ade642

package shared

import (
	"encoding/json"
	"fmt"
)

type ErrorType string

const (
	ErrorTypeValidation     ErrorType = "validation"
	ErrorTypeAuthentication ErrorType = "authentication"
	ErrorTypePermission     ErrorType = "permission"
	ErrorTypeNotFound       ErrorType = "not_found"
	ErrorTypeConflict       ErrorType = "conflict"
	ErrorTypeRateLimited    ErrorType = "rate_limited"
	ErrorTypeRuntime        ErrorType = "runtime"
)

func (e ErrorType) ToPointer() *ErrorType {
	return &e
}
func (e *ErrorType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "validation":
		fallthrough
	case "authentication":
		fallthrough
	case "permission":
		fallthrough
	case "not_found":
		fallthrough
	case "conflict":
		fallthrough
	case "rate_limited":
		fallthrough
	case "runtime":
		*e = ErrorType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ErrorType: %v", v)
	}
}
