// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 941f75eafff0

package shared

type Group struct {
	// The ID of this group.
	ID *string `json:"id,omitempty"`
	// The ID of the app that sources this group.
	AppID *string `json:"app_id,omitempty"`
	// The ID of this group, specific to the integration.
	IntegrationSpecificID *string `json:"integration_specific_id,omitempty"`
	// The name of this group.
	Name *string `json:"name,omitempty"`
	// The description of this group.
	Description *string `json:"description,omitempty"`
	// The lifecycle of this group.
	GroupLifecycle *Lifecycle `json:"group_lifecycle,omitempty"`
	// The ID of the app that sources this group.
	SourceAppID *string `json:"source_app_id,omitempty"`
}

func (g *Group) GetID() *string {
	if g == nil {
		return nil
	}
	return g.ID
}

func (g *Group) GetAppID() *string {
	if g == nil {
		return nil
	}
	return g.AppID
}

func (g *Group) GetIntegrationSpecificID() *string {
	if g == nil {
		return nil
	}
	return g.IntegrationSpecificID
}

func (g *Group) GetName() *string {
	if g == nil {
		return nil
	}
	return g.Name
}

func (g *Group) GetDescription() *string {
	if g == nil {
		return nil
	}
	return g.Description
}

func (g *Group) GetGroupLifecycle() *Lifecycle {
	if g == nil {
		return nil
	}
	return g.GroupLifecycle
}

func (g *Group) GetSourceAppID() *string {
	if g == nil {
		return nil
	}
	return g.SourceAppID
}
