// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type HTTPValidationError struct {
	Detail []ValidationError `json:"detail,omitempty"`
}

func (o *HTTPValidationError) GetDetail() []ValidationError {
	if o == nil {
		return nil
	}
	return o.Detail
}
