// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: f68a07a1c520

package shared

// IntegrationCatalogOutput - A connectable integration from the app catalog (not a connected instance).
//
// Read via `GET /v1/integrations` and `GET /v1/integrations/{app_id}`. Carries
// catalog metadata only — no connection status. To read the state of an
// integration you have connected, use the Apps API (`GET /apps`).
type IntegrationCatalogOutput struct {
	// Canonical identifier of the integration (e.g. `okta.com`). Pass it as `app_id` when connecting via `POST /v1/apps`.
	AppID string `json:"app_id"`
	// Display name of the integration.
	Name string `json:"name"`
	// Short description of the integration.
	Description *string `json:"description,omitempty"`
	// Category of the integration (e.g. `IT & Security`).
	Category *string `json:"category,omitempty"`
	// URL of the integration's logo.
	LogoURL *string `json:"logo_url,omitempty"`
}

func (i *IntegrationCatalogOutput) GetAppID() string {
	if i == nil {
		return ""
	}
	return i.AppID
}

func (i *IntegrationCatalogOutput) GetName() string {
	if i == nil {
		return ""
	}
	return i.Name
}

func (i *IntegrationCatalogOutput) GetDescription() *string {
	if i == nil {
		return nil
	}
	return i.Description
}

func (i *IntegrationCatalogOutput) GetCategory() *string {
	if i == nil {
		return nil
	}
	return i.Category
}

func (i *IntegrationCatalogOutput) GetLogoURL() *string {
	if i == nil {
		return nil
	}
	return i.LogoURL
}
