// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type JobStateOutput struct {
	// The ID of the job.
	JobID string `json:"job_id"`
	// The state of the job.
	State *FlowState `json:"state,omitempty"`
}

func (o *JobStateOutput) GetJobID() string {
	if o == nil {
		return ""
	}
	return o.JobID
}

func (o *JobStateOutput) GetState() *FlowState {
	if o == nil {
		return nil
	}
	return o.State
}
