// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type LimitOffsetPageActivityLog struct {
	Items  []ActivityLog `json:"items"`
	Limit  *int64        `json:"limit,omitempty"`
	Links  Links         `json:"links"`
	Offset *int64        `json:"offset,omitempty"`
	Total  *int64        `json:"total,omitempty"`
}

func (o *LimitOffsetPageActivityLog) GetItems() []ActivityLog {
	if o == nil {
		return []ActivityLog{}
	}
	return o.Items
}

func (o *LimitOffsetPageActivityLog) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *LimitOffsetPageActivityLog) GetLinks() Links {
	if o == nil {
		return Links{}
	}
	return o.Links
}

func (o *LimitOffsetPageActivityLog) GetOffset() *int64 {
	if o == nil {
		return nil
	}
	return o.Offset
}

func (o *LimitOffsetPageActivityLog) GetTotal() *int64 {
	if o == nil {
		return nil
	}
	return o.Total
}
