// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/teamlumos/terraform-provider-lumos/internal/sdk/internal/utils"
	"github.com/teamlumos/terraform-provider-lumos/internal/sdk/types"
)

type LineItemInput struct {
	// The name of the line item as stored in Lumos
	Name string `json:"name"`
	// The type of purchase that this line item refers to
	Type string `json:"type"`
	// The number of units purchased for this line item
	Quantity int64                 `json:"quantity"`
	UnitCost LineItemUnitCostInput `json:"unit_cost"`
	// The start date of the line item
	StartDate types.Date `json:"start_date"`
	// The end date of the line item.
	EndDate *types.Date `json:"end_date"`
}

func (l LineItemInput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *LineItemInput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *LineItemInput) GetName() string {
	if l == nil {
		return ""
	}
	return l.Name
}

func (l *LineItemInput) GetType() string {
	if l == nil {
		return ""
	}
	return l.Type
}

func (l *LineItemInput) GetQuantity() int64 {
	if l == nil {
		return 0
	}
	return l.Quantity
}

func (l *LineItemInput) GetUnitCost() LineItemUnitCostInput {
	if l == nil {
		return LineItemUnitCostInput{}
	}
	return l.UnitCost
}

func (l *LineItemInput) GetStartDate() types.Date {
	if l == nil {
		return types.Date{}
	}
	return l.StartDate
}

func (l *LineItemInput) GetEndDate() *types.Date {
	if l == nil {
		return nil
	}
	return l.EndDate
}
