// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type PagePreApprovalRuleOutput struct {
	Items []PreApprovalRuleOutput `json:"items"`
	Total *int64                  `json:"total"`
	Page  *int64                  `json:"page"`
	Size  *int64                  `json:"size"`
	Pages *int64                  `json:"pages,omitempty"`
}

func (o *PagePreApprovalRuleOutput) GetItems() []PreApprovalRuleOutput {
	if o == nil {
		return []PreApprovalRuleOutput{}
	}
	return o.Items
}

func (o *PagePreApprovalRuleOutput) GetTotal() *int64 {
	if o == nil {
		return nil
	}
	return o.Total
}

func (o *PagePreApprovalRuleOutput) GetPage() *int64 {
	if o == nil {
		return nil
	}
	return o.Page
}

func (o *PagePreApprovalRuleOutput) GetSize() *int64 {
	if o == nil {
		return nil
	}
	return o.Size
}

func (o *PagePreApprovalRuleOutput) GetPages() *int64 {
	if o == nil {
		return nil
	}
	return o.Pages
}
