// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type PageAccount struct {
	Items []Account `json:"items"`
	Total *int64    `json:"total"`
	Page  *int64    `json:"page"`
	Size  *int64    `json:"size"`
	Pages *int64    `json:"pages,omitempty"`
}

func (o *PageAccount) GetItems() []Account {
	if o == nil {
		return []Account{}
	}
	return o.Items
}

func (o *PageAccount) GetTotal() *int64 {
	if o == nil {
		return nil
	}
	return o.Total
}

func (o *PageAccount) GetPage() *int64 {
	if o == nil {
		return nil
	}
	return o.Page
}

func (o *PageAccount) GetSize() *int64 {
	if o == nil {
		return nil
	}
	return o.Size
}

func (o *PageAccount) GetPages() *int64 {
	if o == nil {
		return nil
	}
	return o.Pages
}
