// Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

package shared

type PageRequestablePermissionOutput struct {
	Items []RequestablePermissionOutput `json:"items"`
	Total *int64                        `json:"total,omitempty"`
	Page  *int64                        `json:"page,omitempty"`
	Size  *int64                        `json:"size,omitempty"`
	Pages *int64                        `json:"pages,omitempty"`
}

func (o *PageRequestablePermissionOutput) GetItems() []RequestablePermissionOutput {
	if o == nil {
		return []RequestablePermissionOutput{}
	}
	return o.Items
}

func (o *PageRequestablePermissionOutput) GetTotal() *int64 {
	if o == nil {
		return nil
	}
	return o.Total
}

func (o *PageRequestablePermissionOutput) GetPage() *int64 {
	if o == nil {
		return nil
	}
	return o.Page
}

func (o *PageRequestablePermissionOutput) GetSize() *int64 {
	if o == nil {
		return nil
	}
	return o.Size
}

func (o *PageRequestablePermissionOutput) GetPages() *int64 {
	if o == nil {
		return nil
	}
	return o.Pages
}
