// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type PageVendorAgreement struct {
	Items []VendorAgreement `json:"items"`
	Total *int64            `json:"total"`
	Page  *int64            `json:"page"`
	Size  *int64            `json:"size"`
	Pages *int64            `json:"pages,omitempty"`
}

func (p *PageVendorAgreement) GetItems() []VendorAgreement {
	if p == nil {
		return []VendorAgreement{}
	}
	return p.Items
}

func (p *PageVendorAgreement) GetTotal() *int64 {
	if p == nil {
		return nil
	}
	return p.Total
}

func (p *PageVendorAgreement) GetPage() *int64 {
	if p == nil {
		return nil
	}
	return p.Page
}

func (p *PageVendorAgreement) GetSize() *int64 {
	if p == nil {
		return nil
	}
	return p.Size
}

func (p *PageVendorAgreement) GetPages() *int64 {
	if p == nil {
		return nil
	}
	return p.Pages
}
