// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type PageAppStoreApp struct {
	Items []AppStoreApp `json:"items"`
	Page  *int64        `json:"page,omitempty"`
	Pages *int64        `json:"pages,omitempty"`
	Size  *int64        `json:"size,omitempty"`
	Total *int64        `json:"total,omitempty"`
}

func (o *PageAppStoreApp) GetItems() []AppStoreApp {
	if o == nil {
		return []AppStoreApp{}
	}
	return o.Items
}

func (o *PageAppStoreApp) GetPage() *int64 {
	if o == nil {
		return nil
	}
	return o.Page
}

func (o *PageAppStoreApp) GetPages() *int64 {
	if o == nil {
		return nil
	}
	return o.Pages
}

func (o *PageAppStoreApp) GetSize() *int64 {
	if o == nil {
		return nil
	}
	return o.Size
}

func (o *PageAppStoreApp) GetTotal() *int64 {
	if o == nil {
		return nil
	}
	return o.Total
}
