// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: e1f17b41d203

package shared

type PageAppWithCustomAttributes struct {
	Items []AppWithCustomAttributes `json:"items"`
	Total *int64                    `json:"total"`
	Page  *int64                    `json:"page"`
	Size  *int64                    `json:"size"`
	Pages *int64                    `json:"pages,omitempty"`
}

func (p *PageAppWithCustomAttributes) GetItems() []AppWithCustomAttributes {
	if p == nil {
		return []AppWithCustomAttributes{}
	}
	return p.Items
}

func (p *PageAppWithCustomAttributes) GetTotal() *int64 {
	if p == nil {
		return nil
	}
	return p.Total
}

func (p *PageAppWithCustomAttributes) GetPage() *int64 {
	if p == nil {
		return nil
	}
	return p.Page
}

func (p *PageAppWithCustomAttributes) GetSize() *int64 {
	if p == nil {
		return nil
	}
	return p.Size
}

func (p *PageAppWithCustomAttributes) GetPages() *int64 {
	if p == nil {
		return nil
	}
	return p.Pages
}
