// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 775c42a35923

package shared

import (
	"github.com/teamlumos/terraform-provider-lumos/internal/sdk/internal/utils"
)

// PositionalWeekday - A positional weekday for monthly/yearly recurrences — e.g. "the first Monday of the
// month" is “{"weekday": 0, "n": 1}“. Mirrors “dateutil.rrule.weekday“.
//
// A plain integer weekday (0–6) covers the common case; this richer form is only needed
// when an Nth-occurrence qualifier is present, which a bare int cannot express.
type PositionalWeekday struct {
	// 0=Monday, 1=Tuesday, ..., 6=Sunday.
	Weekday int64 `json:"weekday"`
	// Which occurrence of the weekday within the period (e.g. 1 = first, -1 = last). None means every matching weekday.
	N *int64 `json:"n,omitempty"`
}

func (p PositionalWeekday) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PositionalWeekday) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PositionalWeekday) GetWeekday() int64 {
	if p == nil {
		return 0
	}
	return p.Weekday
}

func (p *PositionalWeekday) GetN() *int64 {
	if p == nil {
		return nil
	}
	return p.N
}
