// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 8969d9b72e4c

package shared

import (
	"github.com/teamlumos/terraform-provider-lumos/internal/sdk/internal/utils"
)

type ReassignTaskInput struct {
	// IDs of users to assign.
	UserIds []string `json:"user_ids,omitempty"`
	// IDs of groups to assign.
	GroupIds []string `json:"group_ids,omitempty"`
	// Whether to replace existing assignees or add to them.
	Replace *bool `default:"true" json:"replace"`
}

func (r ReassignTaskInput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *ReassignTaskInput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *ReassignTaskInput) GetUserIds() []string {
	if r == nil {
		return nil
	}
	return r.UserIds
}

func (r *ReassignTaskInput) GetGroupIds() []string {
	if r == nil {
		return nil
	}
	return r.GroupIds
}

func (r *ReassignTaskInput) GetReplace() *bool {
	if r == nil {
		return nil
	}
	return r.Replace
}
