// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type RequestablePermissionBase struct {
	// The ID of this requestable permission.
	ID *string `json:"id,omitempty"`
}

func (o *RequestablePermissionBase) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}
