// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type RequestApprovalConfigInput struct {
	// Indicates if approval flow is overridden.
	RequestApprovalConfigOverride *bool `json:"request_approval_config_override,omitempty"`
	// Manager approval can be configured as necessary to continue
	ManagerApproval *ManagerApprovalOption `json:"manager_approval,omitempty"`
	// Only turn on when working with sensitive permissions to ensure a smooth employee experience.
	RequireAdditionalApproval *bool `json:"require_additional_approval,omitempty"`
	// After the approval step, send a custom message to requesters. Note that the permission level approval message will override the App level approval message if custom_approval_message_override is set. Markdown for links and text formatting is supported.
	CustomApprovalMessage *string `json:"custom_approval_message,omitempty"`
	// Indicates if custom_approval_message is overridden.
	CustomApprovalMessageOverride *bool              `json:"custom_approval_message_override,omitempty"`
	Approvers                     *AppApproversInput `json:"approvers,omitempty"`
	ApproversStage2               *AppApproversInput `json:"approvers_stage_2,omitempty"`
	// The stages of this request approval.
	RequestApprovalStages []RequestApprovalStageInput `json:"request_approval_stages,omitempty"`
}

func (o *RequestApprovalConfigInput) GetRequestApprovalConfigOverride() *bool {
	if o == nil {
		return nil
	}
	return o.RequestApprovalConfigOverride
}

func (o *RequestApprovalConfigInput) GetManagerApproval() *ManagerApprovalOption {
	if o == nil {
		return nil
	}
	return o.ManagerApproval
}

func (o *RequestApprovalConfigInput) GetRequireAdditionalApproval() *bool {
	if o == nil {
		return nil
	}
	return o.RequireAdditionalApproval
}

func (o *RequestApprovalConfigInput) GetCustomApprovalMessage() *string {
	if o == nil {
		return nil
	}
	return o.CustomApprovalMessage
}

func (o *RequestApprovalConfigInput) GetCustomApprovalMessageOverride() *bool {
	if o == nil {
		return nil
	}
	return o.CustomApprovalMessageOverride
}

func (o *RequestApprovalConfigInput) GetApprovers() *AppApproversInput {
	if o == nil {
		return nil
	}
	return o.Approvers
}

func (o *RequestApprovalConfigInput) GetApproversStage2() *AppApproversInput {
	if o == nil {
		return nil
	}
	return o.ApproversStage2
}

func (o *RequestApprovalConfigInput) GetRequestApprovalStages() []RequestApprovalStageInput {
	if o == nil {
		return nil
	}
	return o.RequestApprovalStages
}
