// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: b7a5c8f7610d

package shared

import (
	"encoding/json"
	"fmt"
)

type ReviewType string

const (
	ReviewTypeAccounts     ReviewType = "ACCOUNTS"
	ReviewTypeEntitlements ReviewType = "ENTITLEMENTS"
)

func (e ReviewType) ToPointer() *ReviewType {
	return &e
}
func (e *ReviewType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ACCOUNTS":
		fallthrough
	case "ENTITLEMENTS":
		*e = ReviewType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ReviewType: %v", v)
	}
}
