// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: a76fd2145f6c

package shared

type TaskAction struct {
	// The external identifier for this action type.
	ActionType string `json:"action_type"`
	// The possible status transitions for this action.
	Transitions []TaskActionTransition `json:"transitions"`
}

func (t *TaskAction) GetActionType() string {
	if t == nil {
		return ""
	}
	return t.ActionType
}

func (t *TaskAction) GetTransitions() []TaskActionTransition {
	if t == nil {
		return []TaskActionTransition{}
	}
	return t.Transitions
}
