// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 10767807eeb2

package shared

type TaskAssignee struct {
	// The ID of the assignee.
	ID   string           `json:"id"`
	Type TaskAssigneeType `json:"type"`
	// The display name of the assignee.
	Name *string `json:"name,omitempty"`
	// The email of the assignee. Only set for users.
	Email *string `json:"email,omitempty"`
}

func (t *TaskAssignee) GetID() string {
	if t == nil {
		return ""
	}
	return t.ID
}

func (t *TaskAssignee) GetType() TaskAssigneeType {
	if t == nil {
		return TaskAssigneeType("")
	}
	return t.Type
}

func (t *TaskAssignee) GetName() *string {
	if t == nil {
		return nil
	}
	return t.Name
}

func (t *TaskAssignee) GetEmail() *string {
	if t == nil {
		return nil
	}
	return t.Email
}
