// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: ebbf5622a904

package shared

import (
	"github.com/teamlumos/terraform-provider-lumos/internal/sdk/internal/utils"
	"time"
)

type Task struct {
	// The ID of this task.
	ID string `json:"id"`
	// The type of this task.
	TaskType     string       `json:"task_type"`
	TaskCategory TaskCategory `json:"task_category"`
	Status       TaskStatus   `json:"status"`
	// A description of this task.
	Description *string `json:"description,omitempty"`
	// Instructions for completing this task.
	Instructions *string `json:"instructions,omitempty"`
	// The product area this task is related to.
	ProductArea *TaskProductArea `json:"product_area,omitempty"`
	// The app this task is related to.
	App *BaseApp `json:"app,omitempty"`
	// The user this task is about.
	TargetUser *User `json:"target_user,omitempty"`
	// The user who resolved this task.
	ResolvedBy *User `json:"resolved_by,omitempty"`
	// When this task was created.
	CreatedAt time.Time `json:"created_at"`
	// When this task was last updated.
	UpdatedAt time.Time `json:"updated_at"`
	// The assignees of this task. Requires expand=assignees.
	Assignees []TaskAssignee `json:"assignees,omitempty"`
	// Available actions for this task. Requires expand=actions.
	Actions []TaskAction `json:"actions,omitempty"`
	// Comments on this task. Requires expand=comments.
	Comments []TaskComment `json:"comments,omitempty"`
	// The access request this task is associated with, if applicable.
	AccessRequestID *string `json:"access_request_id,omitempty"`
	// The requestable permission this task is associated with, if applicable.
	RequestablePermissionID *string `json:"requestable_permission_id,omitempty"`
}

func (t Task) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *Task) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *Task) GetID() string {
	if t == nil {
		return ""
	}
	return t.ID
}

func (t *Task) GetTaskType() string {
	if t == nil {
		return ""
	}
	return t.TaskType
}

func (t *Task) GetTaskCategory() TaskCategory {
	if t == nil {
		return TaskCategory("")
	}
	return t.TaskCategory
}

func (t *Task) GetStatus() TaskStatus {
	if t == nil {
		return TaskStatus("")
	}
	return t.Status
}

func (t *Task) GetDescription() *string {
	if t == nil {
		return nil
	}
	return t.Description
}

func (t *Task) GetInstructions() *string {
	if t == nil {
		return nil
	}
	return t.Instructions
}

func (t *Task) GetProductArea() *TaskProductArea {
	if t == nil {
		return nil
	}
	return t.ProductArea
}

func (t *Task) GetApp() *BaseApp {
	if t == nil {
		return nil
	}
	return t.App
}

func (t *Task) GetTargetUser() *User {
	if t == nil {
		return nil
	}
	return t.TargetUser
}

func (t *Task) GetResolvedBy() *User {
	if t == nil {
		return nil
	}
	return t.ResolvedBy
}

func (t *Task) GetCreatedAt() time.Time {
	if t == nil {
		return time.Time{}
	}
	return t.CreatedAt
}

func (t *Task) GetUpdatedAt() time.Time {
	if t == nil {
		return time.Time{}
	}
	return t.UpdatedAt
}

func (t *Task) GetAssignees() []TaskAssignee {
	if t == nil {
		return nil
	}
	return t.Assignees
}

func (t *Task) GetActions() []TaskAction {
	if t == nil {
		return nil
	}
	return t.Actions
}

func (t *Task) GetComments() []TaskComment {
	if t == nil {
		return nil
	}
	return t.Comments
}

func (t *Task) GetAccessRequestID() *string {
	if t == nil {
		return nil
	}
	return t.AccessRequestID
}

func (t *Task) GetRequestablePermissionID() *string {
	if t == nil {
		return nil
	}
	return t.RequestablePermissionID
}
