// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: e8d37e77109d

package shared

import (
	"errors"
	"fmt"
	"github.com/teamlumos/terraform-provider-lumos/internal/sdk/internal/utils"
	"time"
)

type ValueOptionValueType string

const (
	ValueOptionValueTypeInteger  ValueOptionValueType = "integer"
	ValueOptionValueTypeNumber   ValueOptionValueType = "number"
	ValueOptionValueTypeDateTime ValueOptionValueType = "date-time"
	ValueOptionValueTypeBoolean  ValueOptionValueType = "boolean"
	ValueOptionValueTypeStr      ValueOptionValueType = "str"
)

type ValueOptionValue struct {
	Integer  *int64     `queryParam:"inline" union:"member"`
	Number   *float64   `queryParam:"inline" union:"member"`
	DateTime *time.Time `queryParam:"inline" union:"member"`
	Boolean  *bool      `queryParam:"inline" union:"member"`
	Str      *string    `queryParam:"inline" union:"member"`

	Type ValueOptionValueType
}

func CreateValueOptionValueInteger(integer int64) ValueOptionValue {
	typ := ValueOptionValueTypeInteger

	return ValueOptionValue{
		Integer: &integer,
		Type:    typ,
	}
}

func CreateValueOptionValueNumber(number float64) ValueOptionValue {
	typ := ValueOptionValueTypeNumber

	return ValueOptionValue{
		Number: &number,
		Type:   typ,
	}
}

func CreateValueOptionValueDateTime(dateTime time.Time) ValueOptionValue {
	typ := ValueOptionValueTypeDateTime

	return ValueOptionValue{
		DateTime: &dateTime,
		Type:     typ,
	}
}

func CreateValueOptionValueBoolean(boolean bool) ValueOptionValue {
	typ := ValueOptionValueTypeBoolean

	return ValueOptionValue{
		Boolean: &boolean,
		Type:    typ,
	}
}

func CreateValueOptionValueStr(str string) ValueOptionValue {
	typ := ValueOptionValueTypeStr

	return ValueOptionValue{
		Str:  &str,
		Type: typ,
	}
}

func (u *ValueOptionValue) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var integer int64 = int64(0)
	if err := utils.UnmarshalJSON(data, &integer, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ValueOptionValueTypeInteger,
			Value: &integer,
		})
	}

	var number float64 = float64(0)
	if err := utils.UnmarshalJSON(data, &number, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ValueOptionValueTypeNumber,
			Value: &number,
		})
	}

	var dateTime time.Time = time.Time{}
	if err := utils.UnmarshalJSON(data, &dateTime, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ValueOptionValueTypeDateTime,
			Value: &dateTime,
		})
	}

	var boolean bool = false
	if err := utils.UnmarshalJSON(data, &boolean, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ValueOptionValueTypeBoolean,
			Value: &boolean,
		})
	}

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ValueOptionValueTypeStr,
			Value: &str,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for ValueOptionValue", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for ValueOptionValue", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(ValueOptionValueType)
	switch best.Type {
	case ValueOptionValueTypeInteger:
		u.Integer = best.Value.(*int64)
		return nil
	case ValueOptionValueTypeNumber:
		u.Number = best.Value.(*float64)
		return nil
	case ValueOptionValueTypeDateTime:
		u.DateTime = best.Value.(*time.Time)
		return nil
	case ValueOptionValueTypeBoolean:
		u.Boolean = best.Value.(*bool)
		return nil
	case ValueOptionValueTypeStr:
		u.Str = best.Value.(*string)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for ValueOptionValue", string(data))
}

func (u ValueOptionValue) MarshalJSON() ([]byte, error) {
	if u.Integer != nil {
		return utils.MarshalJSON(u.Integer, "", true)
	}

	if u.Number != nil {
		return utils.MarshalJSON(u.Number, "", true)
	}

	if u.DateTime != nil {
		return utils.MarshalJSON(u.DateTime, "", true)
	}

	if u.Boolean != nil {
		return utils.MarshalJSON(u.Boolean, "", true)
	}

	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	return nil, errors.New("could not marshal union type ValueOptionValue: all fields are null")
}

// ValueOption - Pydantic model describing a Value Option shape.
//
// Conditions may allow specifying a ValueOption in place of a ConditionValue when
//
//	a human-readable label is desired. If the `value` is otherwise pretty human-readable,
//	then it is fine to define the values directly.
type ValueOption struct {
	Label string           `json:"label"`
	Value ValueOptionValue `json:"value"`
}

func (v ValueOption) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *ValueOption) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *ValueOption) GetLabel() string {
	if v == nil {
		return ""
	}
	return v.Label
}

func (v *ValueOption) GetValue() ValueOptionValue {
	if v == nil {
		return ValueOptionValue{}
	}
	return v.Value
}
