// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 11f19698fa36

package shared

type VendorAgreementCustomAttributeUpdateInput struct {
	// The value to store for this custom attribute. Set to null to remove the value.
	Value *string `json:"value,omitempty"`
}

func (v *VendorAgreementCustomAttributeUpdateInput) GetValue() *string {
	if v == nil {
		return nil
	}
	return v.Value
}
