workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    FastAPI:
        inputs:
            - location: ./original-openapi.json
        overlays:
            - location: ./overlay.yaml
        registry:
            location: registry.speakeasyapi.dev/lumos/lumos/fast-api
targets:
    lumos-terraform-provider-target:
        target: terraform
        source: FastAPI
