workflowVersion: 1.0.0
sources:
    FastAPI:
        inputs:
            - location: ./openapi.json
        registry:
            location: registry.speakeasyapi.dev/lumos/lumos/fast-api
targets:
    my-first-target:
        target: terraform
        source: FastAPI
