// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 33938be72481

package provider

import (
	"context"
	"encoding/json"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	tfTypes "github.com/teamlumos/terraform-provider-lumos/internal/provider/types"
	"github.com/teamlumos/terraform-provider-lumos/internal/sdk/models/operations"
	"github.com/teamlumos/terraform-provider-lumos/internal/sdk/models/shared"
)

func (r *AccessPolicyDataSourceModel) RefreshFromSharedAccessPolicyOutput(ctx context.Context, resp *shared.AccessPolicyOutput) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		accessConditionResult, _ := json.Marshal(resp.AccessCondition)
		r.AccessCondition = jsontypes.NewNormalizedValue(string(accessConditionResult))
		r.Apps = []tfTypes.AccessPolicyAppOutput{}

		for _, appsItem := range resp.Apps {
			var apps tfTypes.AccessPolicyAppOutput

			apps.ID = types.StringValue(appsItem.ID)
			apps.IsPreapproved = types.BoolValue(appsItem.IsPreapproved)
			apps.Permissions = []tfTypes.AccessPolicyPermissionInput{}

			for _, permissionsItem := range appsItem.Permissions {
				var permissions tfTypes.AccessPolicyPermissionInput

				permissions.ID = types.StringPointerValue(permissionsItem.ID)

				apps.Permissions = append(apps.Permissions, permissions)
			}

			r.Apps = append(r.Apps, apps)
		}
		r.BusinessJustification = types.StringValue(resp.BusinessJustification)
		r.ID = types.StringValue(resp.ID)
		r.IsEveryoneCondition = types.BoolValue(resp.IsEveryoneCondition)
		r.Name = types.StringValue(resp.Name)
	}

	return diags
}

func (r *AccessPolicyDataSourceModel) ToOperationsGetAccessPolicyRequest(ctx context.Context) (*operations.GetAccessPolicyRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var id string
	id = r.ID.ValueString()

	out := operations.GetAccessPolicyRequest{
		ID: id,
	}

	return &out, diags
}
