// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 8ae9bedb585c

package provider

import (
	"context"
	"encoding/json"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/teamlumos/terraform-provider-lumos/internal/provider/typeconvert"
	tfTypes "github.com/teamlumos/terraform-provider-lumos/internal/provider/types"
	"github.com/teamlumos/terraform-provider-lumos/internal/sdk/models/operations"
	"github.com/teamlumos/terraform-provider-lumos/internal/sdk/models/shared"
)

func (r *AppResourceModel) RefreshFromSharedApp(ctx context.Context, resp *shared.App) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.AllowMultiplePermissionSelection = types.BoolValue(resp.AllowMultiplePermissionSelection)
		r.AppClassID = types.StringValue(resp.AppClassID)
		r.Category = types.StringPointerValue(resp.Category)
		r.Description = types.StringPointerValue(resp.Description)
		r.Disconnected = types.BoolValue(resp.Disconnected)
		r.ID = types.StringValue(resp.ID)
		r.InstanceID = types.StringValue(resp.InstanceID)
		r.Links.AdminURL = types.StringValue(resp.Links.AdminURL)
		r.Links.Self = types.StringValue(resp.Links.Self)
		r.LogoURL = types.StringPointerValue(resp.LogoURL)
		r.RequestInstructions = types.StringPointerValue(resp.RequestInstructions)
		r.Sources = make([]types.String, 0, len(resp.Sources))
		for _, v := range resp.Sources {
			r.Sources = append(r.Sources, types.StringValue(string(v)))
		}
		r.Status = types.StringValue(string(resp.Status))
		r.UserFriendlyLabel = types.StringValue(resp.UserFriendlyLabel)
		r.WebsiteURL = types.StringPointerValue(resp.WebsiteURL)
	}

	return diags
}

func (r *AppResourceModel) RefreshFromSharedAppWithCustomAttributes(ctx context.Context, resp *shared.AppWithCustomAttributes) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.AllowMultiplePermissionSelection = types.BoolValue(resp.AllowMultiplePermissionSelection)
		r.AppClassID = types.StringValue(resp.AppClassID)
		r.Category = types.StringPointerValue(resp.Category)
		if resp.CustomAttributes != nil {
			r.CustomAttributes = make(map[string]tfTypes.CustomAttribute, len(resp.CustomAttributes))
			for customAttributeKey, customAttributeValue := range resp.CustomAttributes {
				var customAttributeResult tfTypes.CustomAttribute
				customAttributeResult.Type = types.StringValue(string(customAttributeValue.Type))
				if customAttributeValue.Value != nil {
					customAttributeResult.Value = &tfTypes.Value{}
					if customAttributeValue.Value.Str != nil {
						customAttributeResult.Value.Str = types.StringPointerValue(customAttributeValue.Value.Str)
					}
					if customAttributeValue.Value.ArrayOfUser != nil {
						customAttributeResult.Value.ArrayOfUser = []tfTypes.User{}

						for _, arrayOfUserItem := range customAttributeValue.Value.ArrayOfUser {
							var arrayOfUser tfTypes.User

							arrayOfUser.Email = types.StringPointerValue(arrayOfUserItem.Email)
							arrayOfUser.FamilyName = types.StringPointerValue(arrayOfUserItem.FamilyName)
							arrayOfUser.GivenName = types.StringPointerValue(arrayOfUserItem.GivenName)
							arrayOfUser.ID = types.StringValue(arrayOfUserItem.ID)
							if arrayOfUserItem.Status != nil {
								arrayOfUser.Status = types.StringValue(string(*arrayOfUserItem.Status))
							} else {
								arrayOfUser.Status = types.StringNull()
							}

							customAttributeResult.Value.ArrayOfUser = append(customAttributeResult.Value.ArrayOfUser, arrayOfUser)
						}
					}
					if customAttributeValue.Value.DateTime != nil {
						customAttributeResult.Value.DateTime = types.StringValue(typeconvert.TimeToString(customAttributeValue.Value.DateTime))
					}
					if customAttributeValue.Value.Integer != nil {
						customAttributeResult.Value.Integer = types.Int64PointerValue(customAttributeValue.Value.Integer)
					}
				}

				r.CustomAttributes[customAttributeKey] = customAttributeResult
			}
		}
		r.Description = types.StringPointerValue(resp.Description)
		r.Disconnected = types.BoolValue(resp.Disconnected)
		r.ID = types.StringValue(resp.ID)
		r.InstanceID = types.StringValue(resp.InstanceID)
		r.Links.AdminURL = types.StringValue(resp.Links.AdminURL)
		r.Links.Self = types.StringValue(resp.Links.Self)
		r.LogoURL = types.StringPointerValue(resp.LogoURL)
		r.RequestInstructions = types.StringPointerValue(resp.RequestInstructions)
		r.Sources = make([]types.String, 0, len(resp.Sources))
		for _, v := range resp.Sources {
			r.Sources = append(r.Sources, types.StringValue(string(v)))
		}
		r.Status = types.StringValue(string(resp.Status))
		r.UserFriendlyLabel = types.StringValue(resp.UserFriendlyLabel)
		r.WebsiteURL = types.StringPointerValue(resp.WebsiteURL)
	}

	return diags
}

func (r *AppResourceModel) ToOperationsDisconnectAppRequest(ctx context.Context) (*operations.DisconnectAppRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var id string
	id = r.ID.ValueString()

	out := operations.DisconnectAppRequest{
		ID: id,
	}

	return &out, diags
}

func (r *AppResourceModel) ToOperationsGetAppRequest(ctx context.Context) (*operations.GetAppRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var id string
	id = r.ID.ValueString()

	out := operations.GetAppRequest{
		ID: id,
	}

	return &out, diags
}

func (r *AppResourceModel) ToOperationsReconnectAppRequest(ctx context.Context) (*operations.ReconnectAppRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var id string
	id = r.ID.ValueString()

	appInputPut, appInputPutDiags := r.ToSharedAppInputPut(ctx)
	diags.Append(appInputPutDiags...)

	if diags.HasError() {
		return nil, diags
	}

	out := operations.ReconnectAppRequest{
		ID:          id,
		AppInputPut: *appInputPut,
	}

	return &out, diags
}

func (r *AppResourceModel) ToSharedAppInputCreate(ctx context.Context) (*shared.AppInputCreate, diag.Diagnostics) {
	var diags diag.Diagnostics

	name := new(string)
	if !r.Name.IsUnknown() && !r.Name.IsNull() {
		*name = r.Name.ValueString()
	} else {
		name = nil
	}
	category := new(string)
	if !r.Category.IsUnknown() && !r.Category.IsNull() {
		*category = r.Category.ValueString()
	} else {
		category = nil
	}
	description := new(string)
	if !r.Description.IsUnknown() && !r.Description.IsNull() {
		*description = r.Description.ValueString()
	} else {
		description = nil
	}
	logoURL := new(string)
	if !r.LogoURL.IsUnknown() && !r.LogoURL.IsNull() {
		*logoURL = r.LogoURL.ValueString()
	} else {
		logoURL = nil
	}
	websiteURL := new(string)
	if !r.WebsiteURL.IsUnknown() && !r.WebsiteURL.IsNull() {
		*websiteURL = r.WebsiteURL.ValueString()
	} else {
		websiteURL = nil
	}
	requestInstructions := new(string)
	if !r.RequestInstructions.IsUnknown() && !r.RequestInstructions.IsNull() {
		*requestInstructions = r.RequestInstructions.ValueString()
	} else {
		requestInstructions = nil
	}
	appClassID := new(string)
	if !r.AppClassID.IsUnknown() && !r.AppClassID.IsNull() {
		*appClassID = r.AppClassID.ValueString()
	} else {
		appClassID = nil
	}
	var auth interface{}
	if !r.Auth.IsUnknown() && !r.Auth.IsNull() {
		_ = json.Unmarshal([]byte(r.Auth.ValueString()), &auth)
	}
	var settings interface{}
	if !r.Settings.IsUnknown() && !r.Settings.IsNull() {
		_ = json.Unmarshal([]byte(r.Settings.ValueString()), &settings)
	}
	version := new(string)
	if !r.Version.IsUnknown() && !r.Version.IsNull() {
		*version = r.Version.ValueString()
	} else {
		version = nil
	}
	out := shared.AppInputCreate{
		Name:                name,
		Category:            category,
		Description:         description,
		LogoURL:             logoURL,
		WebsiteURL:          websiteURL,
		RequestInstructions: requestInstructions,
		AppClassID:          appClassID,
		Auth:                auth,
		Settings:            settings,
		Version:             version,
	}

	return &out, diags
}

func (r *AppResourceModel) ToSharedAppInputPut(ctx context.Context) (*shared.AppInputPut, diag.Diagnostics) {
	var diags diag.Diagnostics

	name := new(string)
	if !r.Name.IsUnknown() && !r.Name.IsNull() {
		*name = r.Name.ValueString()
	} else {
		name = nil
	}
	category := new(string)
	if !r.Category.IsUnknown() && !r.Category.IsNull() {
		*category = r.Category.ValueString()
	} else {
		category = nil
	}
	description := new(string)
	if !r.Description.IsUnknown() && !r.Description.IsNull() {
		*description = r.Description.ValueString()
	} else {
		description = nil
	}
	logoURL := new(string)
	if !r.LogoURL.IsUnknown() && !r.LogoURL.IsNull() {
		*logoURL = r.LogoURL.ValueString()
	} else {
		logoURL = nil
	}
	websiteURL := new(string)
	if !r.WebsiteURL.IsUnknown() && !r.WebsiteURL.IsNull() {
		*websiteURL = r.WebsiteURL.ValueString()
	} else {
		websiteURL = nil
	}
	requestInstructions := new(string)
	if !r.RequestInstructions.IsUnknown() && !r.RequestInstructions.IsNull() {
		*requestInstructions = r.RequestInstructions.ValueString()
	} else {
		requestInstructions = nil
	}
	appClassID := new(string)
	if !r.AppClassID.IsUnknown() && !r.AppClassID.IsNull() {
		*appClassID = r.AppClassID.ValueString()
	} else {
		appClassID = nil
	}
	var auth interface{}
	if !r.Auth.IsUnknown() && !r.Auth.IsNull() {
		_ = json.Unmarshal([]byte(r.Auth.ValueString()), &auth)
	}
	var settings interface{}
	if !r.Settings.IsUnknown() && !r.Settings.IsNull() {
		_ = json.Unmarshal([]byte(r.Settings.ValueString()), &settings)
	}
	version := new(string)
	if !r.Version.IsUnknown() && !r.Version.IsNull() {
		*version = r.Version.ValueString()
	} else {
		version = nil
	}
	out := shared.AppInputPut{
		Name:                name,
		Category:            category,
		Description:         description,
		LogoURL:             logoURL,
		WebsiteURL:          websiteURL,
		RequestInstructions: requestInstructions,
		AppClassID:          appClassID,
		Auth:                auth,
		Settings:            settings,
		Version:             version,
	}

	return &out, diags
}
