// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 27daea122431

package provider

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	tfTypes "github.com/teamlumos/terraform-provider-lumos/internal/provider/types"
	"github.com/teamlumos/terraform-provider-lumos/internal/sdk"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ datasource.DataSource = &GroupsDataSource{}
var _ datasource.DataSourceWithConfigure = &GroupsDataSource{}

func NewGroupsDataSource() datasource.DataSource {
	return &GroupsDataSource{}
}

// GroupsDataSource is the data source implementation.
type GroupsDataSource struct {
	// Provider configured SDK client.
	client *sdk.Lumos
}

// GroupsDataSourceModel describes the data model.
type GroupsDataSourceModel struct {
	AppID                 types.String    `queryParam:"style=form,explode=true,name=app_id" tfsdk:"app_id"`
	ExactMatch            types.Bool      `queryParam:"style=form,explode=true,name=exact_match" tfsdk:"exact_match"`
	IntegrationSpecificID types.String    `queryParam:"style=form,explode=true,name=integration_specific_id" tfsdk:"integration_specific_id"`
	Items                 []tfTypes.Group `tfsdk:"items"`
	Name                  types.String    `queryParam:"style=form,explode=true,name=name" tfsdk:"name"`
	Page                  types.Int64     `queryParam:"style=form,explode=true,name=page" tfsdk:"page"`
	Pages                 types.Int64     `tfsdk:"pages"`
	Size                  types.Int64     `queryParam:"style=form,explode=true,name=size" tfsdk:"size"`
	Total                 types.Int64     `tfsdk:"total"`
}

// Metadata returns the data source type name.
func (r *GroupsDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_groups"
}

// Schema defines the schema for the data source.
func (r *GroupsDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Groups DataSource",

		Attributes: map[string]schema.Attribute{
			"app_id": schema.StringAttribute{
				Optional:    true,
				Description: `Filters groups by the ID of the app to which they belong.`,
			},
			"exact_match": schema.BoolAttribute{
				Optional:    true,
				Description: `Search filter should be an exact match.`,
			},
			"integration_specific_id": schema.StringAttribute{
				Optional:    true,
				Description: `Filters groups by integration specific ID, e.g. the group's Okta ID.`,
			},
			"items": schema.ListNestedAttribute{
				Computed: true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"app_id": schema.StringAttribute{
							Computed:    true,
							Description: `The ID of the app that sources this group.`,
						},
						"description": schema.StringAttribute{
							Computed:    true,
							Description: `The description of this group.`,
						},
						"group_lifecycle": schema.StringAttribute{
							Computed:    true,
							Description: `The lifecycle of this group.`,
						},
						"id": schema.StringAttribute{
							Computed:    true,
							Description: `The ID of this group.`,
						},
						"integration_specific_id": schema.StringAttribute{
							Computed:    true,
							Description: `The ID of this group, specific to the integration.`,
						},
						"name": schema.StringAttribute{
							Computed:    true,
							Description: `The name of this group.`,
						},
						"source_app_id": schema.StringAttribute{
							Computed:    true,
							Description: `The ID of the app that sources this group.`,
						},
					},
				},
			},
			"name": schema.StringAttribute{
				Optional:    true,
				Description: `Filters groups by name.`,
			},
			"page": schema.Int64Attribute{
				Computed:    true,
				Optional:    true,
				Description: `Page number`,
				Validators: []validator.Int64{
					int64validator.AtLeast(1),
				},
			},
			"pages": schema.Int64Attribute{
				Computed: true,
			},
			"size": schema.Int64Attribute{
				Computed:    true,
				Optional:    true,
				Description: `Page size`,
				Validators: []validator.Int64{
					int64validator.Between(1, 100),
				},
			},
			"total": schema.Int64Attribute{
				Computed: true,
			},
		},
	}
}

func (r *GroupsDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*sdk.Lumos)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected DataSource Configure Type",
			fmt.Sprintf("Expected *sdk.Lumos, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.client = client
}

func (r *GroupsDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data *GroupsDataSourceModel
	var item types.Object

	resp.Diagnostics.Append(req.Config.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	request, requestDiags := data.ToOperationsGetGroupsRequest(ctx)
	resp.Diagnostics.Append(requestDiags...)

	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.Core.GetGroups(ctx, *request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if !(res.PageGroup != nil) {
		resp.Diagnostics.AddError("unexpected response from API. Got an unexpected response body", debugResponse(res.RawResponse))
		return
	}
	resp.Diagnostics.Append(data.RefreshFromSharedPageGroup(ctx, res.PageGroup)...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
