// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/provider"
	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/teamlumos/terraform-provider-lumos/internal/sdk"
	"github.com/teamlumos/terraform-provider-lumos/internal/sdk/models/shared"
	"net/http"
	"os"
)

var _ provider.Provider = &LumosProvider{}

type LumosProvider struct {
	// version is set to the provider version on release, "dev" when the
	// provider is built and ran locally, and "test" when running acceptance
	// testing.
	version string
}

// LumosProviderModel describes the provider data model.
type LumosProviderModel struct {
	ServerURL  types.String `tfsdk:"server_url"`
	HTTPBearer types.String `tfsdk:"http_bearer"`
}

func (p *LumosProvider) Metadata(ctx context.Context, req provider.MetadataRequest, resp *provider.MetadataResponse) {
	resp.TypeName = "lumos"
	resp.Version = p.version
}

func (p *LumosProvider) Schema(ctx context.Context, req provider.SchemaRequest, resp *provider.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: `Lumos: The Lumos provider allows you to manage resources such as Apps, Permissions, and Pre-Approval Rules`,
		Attributes: map[string]schema.Attribute{
			"server_url": schema.StringAttribute{
				MarkdownDescription: "Server URL (defaults to https://api.lumos.com)",
				Optional:            true,
				Required:            false,
			},
			"http_bearer": schema.StringAttribute{
				Sensitive: true,
				Optional:  true,
			},
		},
	}
}

func (p *LumosProvider) Configure(ctx context.Context, req provider.ConfigureRequest, resp *provider.ConfigureResponse) {
	var data LumosProviderModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	ServerURL := data.ServerURL.ValueString()

	if ServerURL == "" {
		ServerURL = "https://api.lumos.com"
	}

	httpBearer := new(string)
	if !data.HTTPBearer.IsUnknown() && !data.HTTPBearer.IsNull() {
		*httpBearer = data.HTTPBearer.ValueString()
	} else {
		if len(os.Getenv("LUMOS_ACCESS_TOKEN")) > 0 {
			*httpBearer = os.Getenv("LUMOS_ACCESS_TOKEN")
		} else {
			httpBearer = nil
		}
	}
	security := shared.Security{
		HTTPBearer: httpBearer,
	}

	opts := []sdk.SDKOption{
		sdk.WithServerURL(ServerURL),
		sdk.WithSecurity(security),
		sdk.WithClient(http.DefaultClient),
	}
	client := sdk.New(opts...)

	resp.DataSourceData = client
	resp.ResourceData = client
}

func (p *LumosProvider) Resources(ctx context.Context) []func() resource.Resource {
	return []func() resource.Resource{
		NewAppResource,
		NewAppStoreAppResource,
		NewPreApprovalRuleResource,
		NewRequestablePermissionResource,
	}
}

func (p *LumosProvider) DataSources(ctx context.Context) []func() datasource.DataSource {
	return []func() datasource.DataSource{
		NewAppDataSource,
		NewAppsDataSource,
		NewAppStoreAppDataSource,
		NewAppStoreAppSettingsDataSource,
		NewGroupDataSource,
		NewGroupsDataSource,
		NewRequestablePermissionDataSource,
		NewRequestablePermissionsDataSource,
		NewUserDataSource,
		NewUsersDataSource,
	}
}

func New(version string) func() provider.Provider {
	return func() provider.Provider {
		return &LumosProvider{
			version: version,
		}
	}
}
