// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: ca89c8b39ea1

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type AccessPolicyPermissionInput struct {
	ID types.String `tfsdk:"id"`
}
