// Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type AddAppToAppStoreInputRequestFlow struct {
	Admins                         *AddAppToAppStoreInputAdmins                     `tfsdk:"admins"`
	AllowedGroups                  *AddAppToAppStoreInputAllowedGroups              `tfsdk:"allowed_groups"`
	Approvers                      *AddAppToAppStoreInputApprovers                  `tfsdk:"approvers"`
	ApproversStage2                *AddAppToAppStoreInputApprovers                  `tfsdk:"approvers_stage_2"`
	CustomApprovalMessage          types.String                                     `tfsdk:"custom_approval_message"`
	Discoverability                types.String                                     `tfsdk:"discoverability"`
	RequestValidationInlineWebhook *AddAppToAppStoreInputAccessRemovalInlineWebhook `tfsdk:"request_validation_inline_webhook"`
	RequireAdditionalApproval      types.Bool                                       `tfsdk:"require_additional_approval"`
	RequireManagerApproval         types.Bool                                       `tfsdk:"require_manager_approval"`
}
