// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 0df184dfa85c

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type AllowedGroupsConfigOutput struct {
	Groups []Group      `tfsdk:"groups"`
	Type   types.String `tfsdk:"type"`
}
