// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type App struct {
	AllowMultiplePermissionSelection types.Bool     `tfsdk:"allow_multiple_permission_selection"`
	AppClassID                       types.String   `tfsdk:"app_class_id"`
	ID                               types.String   `tfsdk:"id"`
	InstanceID                       types.String   `tfsdk:"instance_id"`
	Sources                          []types.String `tfsdk:"sources"`
	Status                           types.String   `tfsdk:"status"`
	UserFriendlyLabel                types.String   `tfsdk:"user_friendly_label"`
}
