// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 30919af32d9d

package types

type AppAdminsInput struct {
	Groups []Group `tfsdk:"groups"`
	Users  []User  `tfsdk:"users"`
}
