// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 9fccbdd66c7c

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type AppStoreAppSettingsProvisioningInput struct {
	AccessRemovalInlineWebhook       *BaseInlineWebhook `tfsdk:"access_removal_inline_webhook"`
	AllowMultiplePermissionSelection types.Bool         `tfsdk:"allow_multiple_permission_selection"`
	CustomProvisioningInstructions   types.String       `tfsdk:"custom_provisioning_instructions"`
	GroupsProvisioning               types.String       `tfsdk:"groups_provisioning"`
	ManualStepsNeeded                types.Bool         `tfsdk:"manual_steps_needed"`
	ProvisioningWebhook              *BaseInlineWebhook `tfsdk:"provisioning_webhook"`
	TimeBasedAccess                  []types.String     `tfsdk:"time_based_access"`
}
