// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 5db9329a639f

package types

type AppApproversInput struct {
	Groups []Group `tfsdk:"groups"`
	Users  []User  `tfsdk:"users"`
}
