// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 918947ed86f3

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type AppLinks struct {
	AdminURL types.String `tfsdk:"admin_url"`
	Self     types.String `tfsdk:"self"`
}
