// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type Group struct {
	AppID                 types.String `tfsdk:"app_id"`
	Description           types.String `tfsdk:"description"`
	GroupLifecycle        types.String `tfsdk:"group_lifecycle"`
	ID                    types.String `tfsdk:"id"`
	IntegrationSpecificID types.String `tfsdk:"integration_specific_id"`
	Name                  types.String `tfsdk:"name"`
	SourceAppID           types.String `tfsdk:"source_app_id"`
}
