// Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type RequestablePermissionInputRequestFulfillmentConfig struct {
	ManualInstructions      types.String                                     `tfsdk:"manual_instructions"`
	ManualStepsNeeded       types.Bool                                       `tfsdk:"manual_steps_needed"`
	ProvisioningGroup       *Group                                           `tfsdk:"provisioning_group"`
	ProvisioningWebhook     *AddAppToAppStoreInputAccessRemovalInlineWebhook `tfsdk:"provisioning_webhook"`
	TimeBasedAccess         []types.String                                   `tfsdk:"time_based_access"`
	TimeBasedAccessOverride types.Bool                                       `tfsdk:"time_based_access_override"`
}
